server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    
spring:
  application:
    name: aulas-auth
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob:
        non_contextual_creation: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/aulas_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: root 